# Generated by Django 4.1.2 on 2022-11-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=2048)),
                ('is_verified', models.IntegerField()),
                ('is_blocked', models.IntegerField()),
                ('time_create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('time_create', models.DateTimeField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('first_price', models.BigIntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='shared/')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('id_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('card_name', models.CharField(max_length=100)),
                ('is_verified', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Auction_detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('price', models.BigIntegerField()),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.account')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auction')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.item'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.account'),
        ),
    ]
